// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnplRW6Lj7YrbYKdrng45-5OT63FwoNDg',
    appId: '1:621781213807:web:5cf33e6c5370d6890c239a',
    messagingSenderId: '621781213807',
    projectId: 'warungkupintar-e5867',
    authDomain: 'warungkupintar-e5867.firebaseapp.com',
    storageBucket: 'warungkupintar-e5867.firebasestorage.app',
    measurementId: 'G-L7QPDLB974',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqCQuVEurY0PuxGiA0_E7hGtAKNOnbrv4',
    appId: '1:621781213807:android:75f25b95573110ee0c239a',
    messagingSenderId: '621781213807',
    projectId: 'warungkupintar-e5867',
    storageBucket: 'warungkupintar-e5867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfuyb314z0m4778gWsX6nr9zpaPC0Uvu0',
    appId: '1:621781213807:ios:8e122eaf42787ebe0c239a',
    messagingSenderId: '621781213807',
    projectId: 'warungkupintar-e5867',
    storageBucket: 'warungkupintar-e5867.firebasestorage.app',
    iosClientId: '621781213807-4vc52ggbgmej44t7vqa3dllqsig885ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.umkmSmartAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfuyb314z0m4778gWsX6nr9zpaPC0Uvu0',
    appId: '1:621781213807:ios:8e122eaf42787ebe0c239a',
    messagingSenderId: '621781213807',
    projectId: 'warungkupintar-e5867',
    storageBucket: 'warungkupintar-e5867.firebasestorage.app',
    iosClientId: '621781213807-4vc52ggbgmej44t7vqa3dllqsig885ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.umkmSmartAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnplRW6Lj7YrbYKdrng45-5OT63FwoNDg',
    appId: '1:621781213807:web:259f23a67988b9f20c239a',
    messagingSenderId: '621781213807',
    projectId: 'warungkupintar-e5867',
    authDomain: 'warungkupintar-e5867.firebaseapp.com',
    storageBucket: 'warungkupintar-e5867.firebasestorage.app',
    measurementId: 'G-K5QEJ0LV4M',
  );

}